2015-02-18 09:27:01,543 INFO  io.prediction.tools.Console$ [main] - Development tree detected. Building built-in engines.
2015-02-18 09:27:01,550 INFO  io.prediction.tools.Console$ [main] - Using command '/home/aditi/PredictionIO/sbt/sbt' at /home/aditi/PredictionIO to build.
2015-02-18 09:27:01,552 INFO  io.prediction.tools.Console$ [main] - If the path above is incorrect, this process will fail.
2015-02-18 09:27:01,561 INFO  io.prediction.tools.Console$ [main] - Going to run: [/home/aditi/PredictionIO/sbt/sbt, engines/publishLocal, engines/assemblyPackageDependency]
2015-03-21 13:31:23,152 INFO  org.elasticsearch.plugins [main] - [Zebediah Killgrave] loaded [], sites []
2015-03-21 13:31:25,831 WARN  org.apache.hadoop.util.NativeCodeLoader [main] - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-03-21 13:31:25,959 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2015-03-21 13:31:25,959 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:host.name=aditi-HP-ProBook-4430s
2015-03-21 13:31:25,960 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:java.version=1.7.0_67
2015-03-21 13:31:25,960 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:java.vendor=Oracle Corporation
2015-03-21 13:31:25,960 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:java.home=/usr/lib/jvm/java-7-oracle/jre
2015-03-21 13:31:25,960 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:java.class.path=/home/aditi/PredictionIO/conf:/home/aditi/PredictionIO/assembly/pio-assembly-0.8.6.jar:/home/aditi/PredictionIO/conf
2015-03-21 13:31:25,960 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:java.library.path=/usr/java/packages/lib/i386:/lib:/usr/lib
2015-03-21 13:31:25,960 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:java.io.tmpdir=/tmp
2015-03-21 13:31:25,960 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:java.compiler=<NA>
2015-03-21 13:31:25,961 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:os.name=Linux
2015-03-21 13:31:25,961 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:os.arch=i386
2015-03-21 13:31:25,961 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:os.version=3.11.0-15-generic
2015-03-21 13:31:25,961 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:user.name=aditi
2015-03-21 13:31:25,961 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:user.home=/home/aditi
2015-03-21 13:31:25,964 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:user.dir=/home/aditi/template-scala-parallel-vanilla/src/main/scala
2015-03-21 13:31:25,965 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=hconnection-0x2478b9, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:25,983 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=hconnection-0x2478b9 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:25,984 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:25,985 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:26,015 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed60006, negotiated timeout = 30000
2015-03-21 13:31:26,936 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing master protocol: MasterService
2015-03-21 13:31:26,936 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing zookeeper sessionid=0x14c3b596ed60006
2015-03-21 13:31:26,958 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed60006 closed
2015-03-21 13:31:26,958 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:27,250 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=hconnection-0x135a933, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:27,250 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=hconnection-0x135a933 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:27,251 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:27,251 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:27,266 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed60007, negotiated timeout = 30000
2015-03-21 13:31:27,435 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=hconnection-0xa4acb5, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:27,435 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=hconnection-0xa4acb5 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:27,436 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:27,436 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:27,453 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed60008, negotiated timeout = 30000
2015-03-21 13:31:27,463 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=catalogtracker-on-hconnection-0xa4acb5, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:27,465 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=catalogtracker-on-hconnection-0xa4acb5 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:27,465 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:27,467 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:27,476 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed60009, negotiated timeout = 30000
2015-03-21 13:31:27,508 INFO  org.apache.hadoop.conf.Configuration.deprecation [main] - hadoop.native.lib is deprecated. Instead, use io.native.lib.available
2015-03-21 13:31:27,765 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing zookeeper sessionid=0x14c3b596ed60008
2015-03-21 13:31:27,827 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed60008 closed
2015-03-21 13:31:27,827 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:28,003 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:28,004 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed60009 closed
2015-03-21 13:31:28,007 INFO  io.prediction.data.storage.hbase.HBLEvents [main] - The table predictionio_eventdata:events_0 doesn't exist yet. Creating now...
2015-03-21 13:31:28,540 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=hconnection-0x10c0da1, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:28,541 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:28,541 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:28,541 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=hconnection-0x10c0da1 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:28,553 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed6000a, negotiated timeout = 30000
2015-03-21 13:31:28,558 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=catalogtracker-on-hconnection-0x10c0da1, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:28,559 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:28,559 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:28,560 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=catalogtracker-on-hconnection-0x10c0da1 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:28,564 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed6000b, negotiated timeout = 30000
2015-03-21 13:31:28,573 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing zookeeper sessionid=0x14c3b596ed6000a
2015-03-21 13:31:28,587 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed6000a closed
2015-03-21 13:31:28,587 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:28,697 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed6000b closed
2015-03-21 13:31:28,697 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:29,044 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=hconnection-0xbfba0d, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:29,044 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=hconnection-0xbfba0d connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:29,045 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:29,045 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:29,116 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed6000c, negotiated timeout = 30000
2015-03-21 13:31:29,119 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=catalogtracker-on-hconnection-0xbfba0d, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:29,119 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=catalogtracker-on-hconnection-0xbfba0d connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:29,119 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:29,120 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:29,126 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed6000d, negotiated timeout = 30000
2015-03-21 13:31:29,146 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing zookeeper sessionid=0x14c3b596ed6000c
2015-03-21 13:31:29,159 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed6000c closed
2015-03-21 13:31:29,159 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:29,269 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed6000d closed
2015-03-21 13:31:29,269 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:29,272 INFO  io.prediction.data.storage.hbase.HBLEvents [main] - Removing table predictionio_eventdata:events_0...
2015-03-21 13:31:29,291 INFO  org.apache.hadoop.hbase.client.HBaseAdmin [main] - Started disable of predictionio_eventdata:events_0
2015-03-21 13:31:29,384 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=hconnection-0x527518, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:29,385 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=hconnection-0x527518 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:29,386 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:29,386 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:29,401 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed6000e, negotiated timeout = 30000
2015-03-21 13:31:29,439 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=catalogtracker-on-hconnection-0x527518, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:29,440 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=catalogtracker-on-hconnection-0x527518 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:29,440 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:29,442 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:29,457 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed6000f, negotiated timeout = 30000
2015-03-21 13:31:29,475 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing zookeeper sessionid=0x14c3b596ed6000e
2015-03-21 13:31:29,489 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:29,489 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed6000e closed
2015-03-21 13:31:29,599 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed6000f closed
2015-03-21 13:31:29,599 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:29,706 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=hconnection-0x1e18938, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:29,708 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:29,709 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:29,710 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=hconnection-0x1e18938 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:29,721 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed60010, negotiated timeout = 30000
2015-03-21 13:31:29,730 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=catalogtracker-on-hconnection-0x1e18938, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:29,731 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=catalogtracker-on-hconnection-0x1e18938 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:29,732 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:29,733 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:29,743 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed60011, negotiated timeout = 30000
2015-03-21 13:31:29,769 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing zookeeper sessionid=0x14c3b596ed60010
2015-03-21 13:31:29,775 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:29,775 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed60010 closed
2015-03-21 13:31:29,886 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:29,886 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed60011 closed
2015-03-21 13:31:30,094 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=hconnection-0x176b42, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:30,096 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=hconnection-0x176b42 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:30,096 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:30,098 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:30,106 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed60012, negotiated timeout = 30000
2015-03-21 13:31:30,114 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=catalogtracker-on-hconnection-0x176b42, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:30,115 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=catalogtracker-on-hconnection-0x176b42 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:30,115 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:30,117 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:30,128 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed60013, negotiated timeout = 30000
2015-03-21 13:31:30,159 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing zookeeper sessionid=0x14c3b596ed60012
2015-03-21 13:31:30,171 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed60012 closed
2015-03-21 13:31:30,171 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:30,282 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed60013 closed
2015-03-21 13:31:30,282 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:30,589 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=hconnection-0x20e05c, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:30,591 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=hconnection-0x20e05c connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:30,591 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:30,592 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:30,601 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed60014, negotiated timeout = 30000
2015-03-21 13:31:30,606 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=30000 watcher=catalogtracker-on-hconnection-0x20e05c, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:31:30,607 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=catalogtracker-on-hconnection-0x20e05c connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:31:30,608 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:31:30,608 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:31:30,623 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed60015, negotiated timeout = 30000
2015-03-21 13:31:30,644 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing zookeeper sessionid=0x14c3b596ed60014
2015-03-21 13:31:30,656 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:30,657 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed60014 closed
2015-03-21 13:31:30,766 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed60015 closed
2015-03-21 13:31:30,766 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:30,769 INFO  org.apache.hadoop.hbase.client.HBaseAdmin [main] - Disabled predictionio_eventdata:events_0
2015-03-21 13:31:30,964 INFO  org.apache.hadoop.hbase.client.HBaseAdmin [main] - Deleted predictionio_eventdata:events_0
2015-03-21 13:31:30,964 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing master protocol: MasterService
2015-03-21 13:31:30,965 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing zookeeper sessionid=0x14c3b596ed60007
2015-03-21 13:31:30,987 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:31:30,987 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed60007 closed
2015-03-21 13:32:29,620 INFO  org.elasticsearch.plugins [main] - [Michael Twoyoungmen] loaded [], sites []
2015-03-21 13:32:31,144 WARN  org.apache.hadoop.util.NativeCodeLoader [main] - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-03-21 13:32:31,188 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2015-03-21 13:32:31,188 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:host.name=aditi-HP-ProBook-4430s
2015-03-21 13:32:31,188 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:java.version=1.7.0_67
2015-03-21 13:32:31,188 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:java.vendor=Oracle Corporation
2015-03-21 13:32:31,188 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:java.home=/usr/lib/jvm/java-7-oracle/jre
2015-03-21 13:32:31,189 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:java.class.path=/home/aditi/PredictionIO/conf:/home/aditi/PredictionIO/assembly/pio-assembly-0.8.6.jar:/home/aditi/PredictionIO/conf
2015-03-21 13:32:31,189 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:java.library.path=/usr/java/packages/lib/i386:/lib:/usr/lib
2015-03-21 13:32:31,189 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:java.io.tmpdir=/tmp
2015-03-21 13:32:31,189 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:java.compiler=<NA>
2015-03-21 13:32:31,189 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:os.name=Linux
2015-03-21 13:32:31,189 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:os.arch=i386
2015-03-21 13:32:31,190 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:os.version=3.11.0-15-generic
2015-03-21 13:32:31,190 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:user.name=aditi
2015-03-21 13:32:31,190 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:user.home=/home/aditi
2015-03-21 13:32:31,192 INFO  org.apache.zookeeper.ZooKeeper [main] - Client environment:user.dir=/home/aditi/template-scala-parallel-vanilla/src/main/scala
2015-03-21 13:32:31,193 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=hconnection-0x1a1007a, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:32:31,208 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=hconnection-0x1a1007a connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:32:31,208 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:32:31,209 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:32:31,231 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed60016, negotiated timeout = 40000
2015-03-21 13:32:31,621 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing master protocol: MasterService
2015-03-21 13:32:31,621 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing zookeeper sessionid=0x14c3b596ed60016
2015-03-21 13:32:31,637 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed60016 closed
2015-03-21 13:32:31,637 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:32:31,805 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=hconnection-0x1216428, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:32:31,806 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:32:31,806 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:32:31,806 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=hconnection-0x1216428 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:32:31,813 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed60017, negotiated timeout = 40000
2015-03-21 13:32:31,900 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=hconnection-0x764b75, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:32:31,901 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=hconnection-0x764b75 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:32:31,901 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:32:31,902 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:32:31,912 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed60018, negotiated timeout = 40000
2015-03-21 13:32:31,920 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=catalogtracker-on-hconnection-0x764b75, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:32:31,920 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=catalogtracker-on-hconnection-0x764b75 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:32:31,921 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:32:31,921 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:32:31,934 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed60019, negotiated timeout = 40000
2015-03-21 13:32:31,964 INFO  org.apache.hadoop.conf.Configuration.deprecation [main] - hadoop.native.lib is deprecated. Instead, use io.native.lib.available
2015-03-21 13:32:32,069 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing zookeeper sessionid=0x14c3b596ed60018
2015-03-21 13:32:32,076 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed60018 closed
2015-03-21 13:32:32,077 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:32:32,187 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed60019 closed
2015-03-21 13:32:32,187 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:32:32,189 INFO  io.prediction.data.storage.hbase.HBLEvents [main] - The table predictionio_eventdata:events_6 doesn't exist yet. Creating now...
2015-03-21 13:32:32,447 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=hconnection-0x12aa2c7, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:32:32,447 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:32:32,448 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:32:32,448 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=hconnection-0x12aa2c7 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:32:32,484 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed6001a, negotiated timeout = 40000
2015-03-21 13:32:32,492 INFO  org.apache.zookeeper.ZooKeeper [main] - Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=catalogtracker-on-hconnection-0x12aa2c7, quorum=localhost:2181, baseZNode=/hbase
2015-03-21 13:32:32,494 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2015-03-21 13:32:32,494 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Socket connection established to localhost/127.0.0.1:2181, initiating session
2015-03-21 13:32:32,494 INFO  org.apache.hadoop.hbase.zookeeper.RecoverableZooKeeper [main] - Process identifier=catalogtracker-on-hconnection-0x12aa2c7 connecting to ZooKeeper ensemble=localhost:2181
2015-03-21 13:32:32,506 INFO  org.apache.zookeeper.ClientCnxn [main-SendThread(localhost:2181)] - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14c3b596ed6001b, negotiated timeout = 40000
2015-03-21 13:32:32,521 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing zookeeper sessionid=0x14c3b596ed6001a
2015-03-21 13:32:32,529 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:32:32,529 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed6001a closed
2015-03-21 13:32:32,639 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:32:32,639 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed6001b closed
2015-03-21 13:32:32,656 INFO  io.prediction.tools.Console$ [main] - Initialized Event Store for this app ID: 6.
2015-03-21 13:32:32,704 INFO  io.prediction.tools.Console$ [main] - Created new app:
2015-03-21 13:32:32,705 INFO  io.prediction.tools.Console$ [main] -       Name: Aditi_Test
2015-03-21 13:32:32,705 INFO  io.prediction.tools.Console$ [main] -         ID: 6
2015-03-21 13:32:32,706 INFO  io.prediction.tools.Console$ [main] - Access Key: 4Aa4Xs0GDgfh7lCgResmmVYLsUJFTBDVQy45uSIHKb5TnOh40LDm5XsIwdeBBB0l
2015-03-21 13:32:32,706 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing master protocol: MasterService
2015-03-21 13:32:32,707 INFO  org.apache.hadoop.hbase.client.HConnectionManager$HConnectionImplementation [main] - Closing zookeeper sessionid=0x14c3b596ed60017
2015-03-21 13:32:32,737 INFO  org.apache.zookeeper.ZooKeeper [main] - Session: 0x14c3b596ed60017 closed
2015-03-21 13:32:32,737 INFO  org.apache.zookeeper.ClientCnxn [main-EventThread] - EventThread shut down
2015-03-21 13:58:26,045 INFO  org.elasticsearch.plugins [main] - [Air-Walker] loaded [], sites []
2015-03-21 13:58:26,891 INFO  io.prediction.tools.Console$ [main] -                 Name |   ID |                                                       Access Key | Allowed Event(s)
2015-03-21 13:58:26,937 INFO  io.prediction.tools.Console$ [main] -               Aditi1 |    7 | txotrXiInOUZxuFoo9eeGGSJEJAqUcqgzZAxyvbpeq55B898XDcSiXB79JngDJoI | (all)
2015-03-21 13:58:26,944 INFO  io.prediction.tools.Console$ [main] -            AditiApp1 |    4 | vcGNRtsvKxa3NG1ZGKCx0Dun6khaVh2ffsG6OIq3iqdcvvxhg3UlaelnAQETZpSd | (all)
2015-03-21 13:58:26,949 INFO  io.prediction.tools.Console$ [main] -           Aditi_App1 |    5 | fFbyS3ZS4FA3APGRc540vR5CoJHXLnRCgqlL7BIRG4VXvEtVviuYTguyy06gZ8Ow | (all)
2015-03-21 13:58:26,956 INFO  io.prediction.tools.Console$ [main] -           Aditi_Test |    6 | 4Aa4Xs0GDgfh7lCgResmmVYLsUJFTBDVQy45uSIHKb5TnOh40LDm5XsIwdeBBB0l | (all)
2015-03-21 13:58:26,961 INFO  io.prediction.tools.Console$ [main] -               MyApp1 |    1 | 43DS5E2jpSIOyuEZW4lSjo7w3VIO788kYo6tkUMzWrZIZqBLu2PwZlNSt4l0YryW | (all)
2015-03-21 13:58:26,965 INFO  io.prediction.tools.Console$ [main] -               MyApp2 |    2 | 5ey701blQ0kLkgRGWxIKe8OTW4dDd4CAkZCDw806jZJNh7eCFiCzcqV7U5DvcfVh | (all)
2015-03-21 13:58:26,970 INFO  io.prediction.tools.Console$ [main] -               MyApp3 |    3 | VRrp4Q0OuuLNrOQwMOnNXRgOyaEIq2opM2Wt1QOTretr0DJEN0xjo02wocajfteS | (all)
2015-03-21 13:58:26,971 INFO  io.prediction.tools.Console$ [main] - Finished listing 7 app(s).
2015-04-16 11:40:02,874 WARN  io.prediction.tools.console.Console$ [main] - This engine project directory contains an auto-generated manifest that has been copied/moved from another location. 
2015-04-16 11:40:02,889 WARN  io.prediction.tools.console.Console$ [main] - Regenerating the manifest to reflect the updated location. This will dissociate with all previous engine instances.
2015-04-16 11:40:03,013 INFO  io.prediction.tools.console.Console$ [main] - Using command '/home/aditi/PredictionIO/sbt/sbt' at the current working directory to build.
2015-04-16 11:40:03,014 INFO  io.prediction.tools.console.Console$ [main] - If the path above is incorrect, this process will fail.
2015-04-16 11:40:03,015 INFO  io.prediction.tools.console.Console$ [main] - Uber JAR disabled. Making sure lib/pio-assembly-0.9.1.jar is absent.
2015-04-16 11:40:03,016 INFO  io.prediction.tools.console.Console$ [main] - Going to run: /home/aditi/PredictionIO/sbt/sbt  package assemblyPackageDependency
2015-04-18 16:31:53,235 INFO  io.prediction.tools.console.Console$ [main] - Using existing engine manifest JSON at /home/aditi/job_prediction_pio/src/main/scala/manifest.json
2015-04-18 16:31:53,257 INFO  io.prediction.tools.console.Console$ [main] - Using command '/home/aditi/PredictionIO/sbt/sbt' at the current working directory to build.
2015-04-18 16:31:53,258 INFO  io.prediction.tools.console.Console$ [main] - If the path above is incorrect, this process will fail.
2015-04-18 16:31:53,259 INFO  io.prediction.tools.console.Console$ [main] - Uber JAR disabled. Making sure lib/pio-assembly-0.9.1.jar is absent.
2015-04-18 16:31:53,260 INFO  io.prediction.tools.console.Console$ [main] - Going to run: /home/aditi/PredictionIO/sbt/sbt  package assemblyPackageDependency
2015-04-18 16:31:53,699 DEBUG io.prediction.workflow.UpgradeCheckRunner [Thread-0] - Update metainfo not found. http://direct.prediction.io/0.9.1/build.json
2015-04-18 16:31:56,256 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[0minfo[0m] [0mSet current project to scala (in build file:/home/aditi/job_prediction_pio/src/main/scala/)[0m
2015-04-18 16:31:56,821 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[0minfo[0m] [0mUpdating {file:/home/aditi/job_prediction_pio/src/main/scala/}scala...[0m
2015-04-18 16:31:57,053 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[0minfo[0m] [0mResolving org.scala-lang#scala-library;2.10.4 ...[0m
2015-04-18 16:31:57,369 INFO  io.prediction.tools.console.Console$ [Thread-2] - 
2015-04-18 16:31:57,369 INFO  io.prediction.tools.console.Console$ [Thread-2] - M[2K[0m[[0minfo[0m] [0mResolving org.scala-lang#scala-compiler;2.10.4 ...[0m
2015-04-18 16:31:57,425 INFO  io.prediction.tools.console.Console$ [Thread-2] - 
2015-04-18 16:31:57,426 INFO  io.prediction.tools.console.Console$ [Thread-2] - M[2K[0m[[0minfo[0m] [0mResolving org.scala-lang#scala-reflect;2.10.4 ...[0m
2015-04-18 16:31:57,464 INFO  io.prediction.tools.console.Console$ [Thread-2] - 
2015-04-18 16:31:57,464 INFO  io.prediction.tools.console.Console$ [Thread-2] - M[2K[0m[[0minfo[0m] [0mResolving org.scala-lang#jline;2.10.4 ...[0m
2015-04-18 16:31:57,506 INFO  io.prediction.tools.console.Console$ [Thread-2] - 
2015-04-18 16:31:57,506 INFO  io.prediction.tools.console.Console$ [Thread-2] - M[2K[0m[[0minfo[0m] [0mResolving org.fusesource.jansi#jansi;1.4 ...[0m
2015-04-18 16:31:57,617 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[0minfo[0m] [0mDone updating.[0m
2015-04-18 16:31:57,808 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[0minfo[0m] [0mCompiling 5 Scala sources to /home/aditi/job_prediction_pio/src/main/scala/target/scala-2.10/classes...[0m
2015-04-18 16:31:58,781 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:3: object prediction is not a member of package io[0m
2015-04-18 16:31:58,782 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport io.prediction.controller.P2LAlgorithm[0m
2015-04-18 16:31:58,782 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:58,784 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:4: object prediction is not a member of package io[0m
2015-04-18 16:31:58,785 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport io.prediction.controller.Params[0m
2015-04-18 16:31:58,785 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:58,786 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:7: object apache is not a member of package org[0m
2015-04-18 16:31:58,786 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.mllib.regression.LinearRegressionWithSGD[0m
2015-04-18 16:31:58,786 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:58,787 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:8: object apache is not a member of package org[0m
2015-04-18 16:31:58,787 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.mllib.regression.LinearRegressionModel[0m
2015-04-18 16:31:58,787 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:58,788 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:9: object apache is not a member of package org[0m
2015-04-18 16:31:58,788 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.mllib.linalg.Vectors[0m
2015-04-18 16:31:58,788 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:58,789 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:10: object apache is not a member of package org[0m
2015-04-18 16:31:58,789 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.SparkContext[0m
2015-04-18 16:31:58,789 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:58,790 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:11: object apache is not a member of package org[0m
2015-04-18 16:31:58,790 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.SparkContext._[0m
2015-04-18 16:31:58,790 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:58,791 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:13: object apache is not a member of package org[0m
2015-04-18 16:31:58,791 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.SparkContext[0m
2015-04-18 16:31:58,791 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:58,793 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:14: not found: object grizzled[0m
2015-04-18 16:31:58,793 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport grizzled.slf4j.Logger[0m
2015-04-18 16:31:58,793 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m       ^[0m
2015-04-18 16:31:58,794 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:15: object apache is not a member of package org[0m
2015-04-18 16:31:58,794 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.mllib.regression.LabeledPoint[0m
2015-04-18 16:31:58,794 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:58,796 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:22: not found: type Params[0m
2015-04-18 16:31:58,797 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m) extends Params[0m
2015-04-18 16:31:58,797 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:58,970 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:28: not found: type P2LAlgorithm[0m
2015-04-18 16:31:58,970 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m  extends P2LAlgorithm[PreparedData, LinearRegressionModel, Query, PredictedResult] {[0m
2015-04-18 16:31:58,970 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:58,974 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:30: not found: value Logger[0m
2015-04-18 16:31:58,974 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m  @transient lazy val logger = Logger[this.type][0m
2015-04-18 16:31:58,974 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                               ^[0m
2015-04-18 16:31:58,979 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:32: not found: type LinearRegressionModel[0m
2015-04-18 16:31:58,979 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m  def train(sc:SparkContext, data: PreparedData): LinearRegressionModel = {[0m
2015-04-18 16:31:58,980 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                                                  ^[0m
2015-04-18 16:31:58,980 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:32: not found: type SparkContext[0m
2015-04-18 16:31:58,980 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m  def train(sc:SparkContext, data: PreparedData): LinearRegressionModel = {[0m
2015-04-18 16:31:58,981 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m               ^[0m
2015-04-18 16:31:58,982 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Preparator.scala:6: object apache is not a member of package org[0m
2015-04-18 16:31:58,982 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.SparkContext._[0m
2015-04-18 16:31:58,982 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:59,277 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Preparator.scala:7: object apache is not a member of package org[0m
2015-04-18 16:31:59,278 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.rdd.RDD[0m
2015-04-18 16:31:59,278 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:59,278 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Preparator.scala:12: not found: type RDD[0m
2015-04-18 16:31:59,278 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m  val training_points: RDD[Point_Features][0m
2015-04-18 16:31:59,279 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                       ^[0m
2015-04-18 16:31:59,284 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:38: not found: type LinearRegressionWithSGD[0m
2015-04-18 16:31:59,284 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m    val lin = new LinearRegressionWithSGD() [0m
2015-04-18 16:31:59,284 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                  ^[0m
2015-04-18 16:31:59,286 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Algorithm.scala:59: not found: type LinearRegressionModel[0m
2015-04-18 16:31:59,286 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m  def predict(model: LinearRegressionModel, query: Query): PredictedResult = {[0m
2015-04-18 16:31:59,286 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                     ^[0m
2015-04-18 16:31:59,348 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:3: object prediction is not a member of package io[0m
2015-04-18 16:31:59,348 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport io.prediction.controller.PDataSource[0m
2015-04-18 16:31:59,348 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:59,349 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:4: object prediction is not a member of package io[0m
2015-04-18 16:31:59,349 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport io.prediction.controller.EmptyEvaluationInfo[0m
2015-04-18 16:31:59,349 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:59,351 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:5: object prediction is not a member of package io[0m
2015-04-18 16:31:59,351 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport io.prediction.controller.EmptyActualResult[0m
2015-04-18 16:31:59,351 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:59,352 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:6: object prediction is not a member of package io[0m
2015-04-18 16:31:59,352 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport io.prediction.controller.Params[0m
2015-04-18 16:31:59,352 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:59,353 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:7: object prediction is not a member of package io[0m
2015-04-18 16:31:59,354 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport io.prediction.data.storage.Event[0m
2015-04-18 16:31:59,354 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:59,355 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:8: object prediction is not a member of package io[0m
2015-04-18 16:31:59,365 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport io.prediction.data.storage.Storage[0m
2015-04-18 16:31:59,365 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:59,365 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:10: object apache is not a member of package org[0m
2015-04-18 16:31:59,365 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.SparkContext[0m
2015-04-18 16:31:59,365 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:59,366 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:11: object apache is not a member of package org[0m
2015-04-18 16:31:59,366 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.SparkContext._[0m
2015-04-18 16:31:59,366 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:59,366 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:12: object apache is not a member of package org[0m
2015-04-18 16:31:59,366 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.rdd.RDD[0m
2015-04-18 16:31:59,367 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:59,367 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:13: object apache is not a member of package org[0m
2015-04-18 16:31:59,367 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.mllib.regression.LabeledPoint[0m
2015-04-18 16:31:59,367 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:59,367 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:14: object apache is not a member of package org[0m
2015-04-18 16:31:59,367 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.mllib.linalg.Vectors[0m
2015-04-18 16:31:59,368 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:59,368 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:16: not found: object grizzled[0m
2015-04-18 16:31:59,368 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport grizzled.slf4j.Logger[0m
2015-04-18 16:31:59,368 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m       ^[0m
2015-04-18 16:31:59,368 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:18: not found: type Params[0m
2015-04-18 16:31:59,368 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mcase class DataSourceParams(val appId: Int) extends Params[0m
2015-04-18 16:31:59,369 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                                                    ^[0m
2015-04-18 16:31:59,398 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:21: not found: type PDataSource[0m
2015-04-18 16:31:59,398 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m  extends PDataSource[TrainingData,[0m
2015-04-18 16:31:59,399 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:59,402 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:24: not found: value Logger[0m
2015-04-18 16:31:59,402 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m  @transient lazy val logger = Logger[this.type][0m
2015-04-18 16:31:59,403 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                               ^[0m
2015-04-18 16:31:59,405 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:27: not found: type SparkContext[0m
2015-04-18 16:31:59,406 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m  def readTraining(sc: SparkContext): TrainingData = {[0m
2015-04-18 16:31:59,406 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                       ^[0m
2015-04-18 16:31:59,409 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:28: not found: value Storage[0m
2015-04-18 16:31:59,409 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m    val eventsDb = Storage.getPEvents()[0m
2015-04-18 16:31:59,409 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                   ^[0m
2015-04-18 16:31:59,411 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:37: not found: type RDD[0m
2015-04-18 16:31:59,412 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m    val training_points: RDD[Point_Features] = eventsDb.aggregateProperties([0m
2015-04-18 16:31:59,412 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                         ^[0m
2015-04-18 16:31:59,415 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/DataSource.scala:92: not found: type RDD[0m
2015-04-18 16:31:59,415 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m  val training_points: RDD[Point_Features][0m
2015-04-18 16:31:59,416 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                       ^[0m
2015-04-18 16:31:59,491 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Engine.scala:5: object prediction is not a member of package io[0m
2015-04-18 16:31:59,491 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport io.prediction.controller.IEngineFactory[0m
2015-04-18 16:31:59,492 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:59,493 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Engine.scala:6: object prediction is not a member of package io[0m
2015-04-18 16:31:59,493 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport io.prediction.controller.Engine[0m
2015-04-18 16:31:59,493 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:59,498 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Engine.scala:16: not found: type IEngineFactory[0m
2015-04-18 16:31:59,498 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mobject VanillaEngine extends IEngineFactory {[0m
2015-04-18 16:31:59,498 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                             ^[0m
2015-04-18 16:31:59,500 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Engine.scala:18: not found: type Engine[0m
2015-04-18 16:31:59,500 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m    new Engine([0m
2015-04-18 16:31:59,500 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m        ^[0m
2015-04-18 16:31:59,502 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Preparator.scala:3: object prediction is not a member of package io[0m
2015-04-18 16:31:59,502 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport io.prediction.controller.PPreparator[0m
2015-04-18 16:31:59,502 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:59,503 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Preparator.scala:5: object apache is not a member of package org[0m
2015-04-18 16:31:59,503 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.SparkContext[0m
2015-04-18 16:31:59,503 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:59,504 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Preparator.scala:8: object apache is not a member of package org[0m
2015-04-18 16:31:59,504 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport org.apache.spark.mllib.regression.LabeledPoint[0m
2015-04-18 16:31:59,504 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m           ^[0m
2015-04-18 16:31:59,507 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Preparator.scala:16: not found: type PPreparator[0m
2015-04-18 16:31:59,508 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mclass Preparator extends PPreparator[TrainingData, PreparedData] {[0m
2015-04-18 16:31:59,508 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                         ^[0m
2015-04-18 16:31:59,510 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Preparator.scala:18: not found: type SparkContext[0m
2015-04-18 16:31:59,510 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m  def prepare(sc: SparkContext, trainingData: TrainingData) : PreparedData =  {[0m
2015-04-18 16:31:59,510 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                  ^[0m
2015-04-18 16:31:59,643 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Serving.scala:3: object prediction is not a member of package io[0m
2015-04-18 16:31:59,644 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mimport io.prediction.controller.LServing[0m
2015-04-18 16:31:59,644 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m          ^[0m
2015-04-18 16:31:59,645 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m/home/aditi/job_prediction_pio/src/main/scala/Serving.scala:5: not found: type LServing[0m
2015-04-18 16:31:59,646 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mclass Serving extends LServing[Query, PredictedResult] {[0m
2015-04-18 16:31:59,646 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m                      ^[0m
2015-04-18 16:31:59,670 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m50 errors found[0m
2015-04-18 16:31:59,714 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0m(compile:[31mcompile[0m) Compilation failed[0m
2015-04-18 16:31:59,720 INFO  io.prediction.tools.console.Console$ [Thread-2] - [0m[[31merror[0m] [0mTotal time: 3 s, completed Apr 18, 2015 4:31:59 PM[0m
2015-04-18 16:31:59,747 ERROR io.prediction.tools.console.Console$ [main] - Return code of previous step is 1. Aborting.
